import React, { useState, useEffect } from 'react';
import FigureArticle from './FigureArticle';

function MainContent() {

    const content = [
        {one: 'DEEP', two: 'EARTH', desktop: 'https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fmakaia-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!pHMaEJJFGE6APq-ucNaeRkfabKWyzh5Oujdv51iLYXtgn0x5alXYRJWndspysbld%2Fitems%2F01RG7JYSOOTKRQLB6XGVAJOHTGLVAJ6DVZ%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWFrYWlhLW15LnNoYXJlcG9pbnQuY29tQDBhNzI2YzNlLTI5YzItNDhjMS05ZDNlLWU4OGVjNjUxYzQyMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTQ4MDA4MDAiLCJleHAiOiIxNjk0ODIyNDAwIiwiZW5kcG9pbnR1cmwiOiJaeVlNeG1WQnArTmJwcU9OMG1jQzFTT1hEK1l4eTVQSDEwRWc0cnRrcWJvPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRBeFlUY3pZVFF0TkRVNU1pMDBaVEU0TFRnd00yVXRZV1poWlRjd1pEWTVaVFEyIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsInNoYXJpbmdpZCI6IkdIYWE4TUNLYUU2VDgxQVBjQVZ2TkEiLCJ0dCI6IjAiLCJpcGFkZHIiOiIxODYuMTkwLjIyNi4zNSJ9.Bhxha8b2_frC5JJTNo9-S0LHEfrpYBHDCPbaNQSesdw&cTag=%22c%3A%7B05A39ACE-D787-4035-971E-665D409F0EB9%7D%2C2%22&encodeFailures=1&width=256&height=450&srcWidth=256&srcHeight=450', mobile: '../public/mobile/image-deep-earth.jpg'},
        {one: 'NIGHT', two: 'ARCADE', desktop: 'https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fmakaia-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!pHMaEJJFGE6APq-ucNaeRkfabKWyzh5Oujdv51iLYXtgn0x5alXYRJWndspysbld%2Fitems%2F01RG7JYSIGPLGTU4PYEZBIY2ISXDTMRNUV%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWFrYWlhLW15LnNoYXJlcG9pbnQuY29tQDBhNzI2YzNlLTI5YzItNDhjMS05ZDNlLWU4OGVjNjUxYzQyMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTQ4MDA4MDAiLCJleHAiOiIxNjk0ODIyNDAwIiwiZW5kcG9pbnR1cmwiOiJaeVlNeG1WQnArTmJwcU9OMG1jQzFTT1hEK1l4eTVQSDEwRWc0cnRrcWJvPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRBeFlUY3pZVFF0TkRVNU1pMDBaVEU0TFRnd00yVXRZV1poWlRjd1pEWTVaVFEyIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsInNoYXJpbmdpZCI6IkdIYWE4TUNLYUU2VDgxQVBjQVZ2TkEiLCJ0dCI6IjAiLCJpcGFkZHIiOiIxODYuMTkwLjIyNi4zNSJ9.Bhxha8b2_frC5JJTNo9-S0LHEfrpYBHDCPbaNQSesdw&cTag=%22c%3A%7B3ACD7A06-F871-4226-8C69-12B8E6C8B695%7D%2C2%22&encodeFailures=1&width=256&height=450&srcWidth=256&srcHeight=450', mobile: '../public/mobile/image-night-arcade.jpg'},
        {one: 'SOCCER', two: 'TEAM VR', desktop: 'https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fmakaia-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!pHMaEJJFGE6APq-ucNaeRkfabKWyzh5Oujdv51iLYXtgn0x5alXYRJWndspysbld%2Fitems%2F01RG7JYSMFKRD3AK4VVVGJ2OTV3AEOCKRC%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWFrYWlhLW15LnNoYXJlcG9pbnQuY29tQDBhNzI2YzNlLTI5YzItNDhjMS05ZDNlLWU4OGVjNjUxYzQyMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTQ4MDA4MDAiLCJleHAiOiIxNjk0ODIyNDAwIiwiZW5kcG9pbnR1cmwiOiJaeVlNeG1WQnArTmJwcU9OMG1jQzFTT1hEK1l4eTVQSDEwRWc0cnRrcWJvPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRBeFlUY3pZVFF0TkRVNU1pMDBaVEU0TFRnd00yVXRZV1poWlRjd1pEWTVaVFEyIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsInNoYXJpbmdpZCI6IkdIYWE4TUNLYUU2VDgxQVBjQVZ2TkEiLCJ0dCI6IjAiLCJpcGFkZHIiOiIxODYuMTkwLjIyNi4zNSJ9.Bhxha8b2_frC5JJTNo9-S0LHEfrpYBHDCPbaNQSesdw&cTag=%22c%3A%7BB0475485-952B-4CAD-9D3A-75D808E12A22%7D%2C2%22&encodeFailures=1&width=256&height=450&srcWidth=256&srcHeight=450', mobile: '../public/mobile/image-soccer-team.jpg'},
        {one: 'THE', two: 'GRID', desktop: 'https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fmakaia-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!pHMaEJJFGE6APq-ucNaeRkfabKWyzh5Oujdv51iLYXtgn0x5alXYRJWndspysbld%2Fitems%2F01RG7JYSIQTGSKGYBUKRH3X6VV6Z5WJUL6%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWFrYWlhLW15LnNoYXJlcG9pbnQuY29tQDBhNzI2YzNlLTI5YzItNDhjMS05ZDNlLWU4OGVjNjUxYzQyMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTQ4MDA4MDAiLCJleHAiOiIxNjk0ODIyNDAwIiwiZW5kcG9pbnR1cmwiOiJaeVlNeG1WQnArTmJwcU9OMG1jQzFTT1hEK1l4eTVQSDEwRWc0cnRrcWJvPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRBeFlUY3pZVFF0TkRVNU1pMDBaVEU0TFRnd00yVXRZV1poWlRjd1pEWTVaVFEyIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsInNoYXJpbmdpZCI6IkdIYWE4TUNLYUU2VDgxQVBjQVZ2TkEiLCJ0dCI6IjAiLCJpcGFkZHIiOiIxODYuMTkwLjIyNi4zNSJ9.Bhxha8b2_frC5JJTNo9-S0LHEfrpYBHDCPbaNQSesdw&cTag=%22c%3A%7BA3A49910-3460-4F54-BBFA-B5F67B64D17E%7D%2C2%22&encodeFailures=1&width=256&height=450&srcWidth=256&srcHeight=450', mobile: '../public/mobile/image-grid.jpg'},
        {one: 'FROM UP', two: 'ABOVE VR', desktop: 'https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fmakaia-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!pHMaEJJFGE6APq-ucNaeRkfabKWyzh5Oujdv51iLYXtgn0x5alXYRJWndspysbld%2Fitems%2F01RG7JYSJ6QOTD567KVRFLCOHMPAVZ6RKN%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWFrYWlhLW15LnNoYXJlcG9pbnQuY29tQDBhNzI2YzNlLTI5YzItNDhjMS05ZDNlLWU4OGVjNjUxYzQyMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTQ4MDA4MDAiLCJleHAiOiIxNjk0ODIyNDAwIiwiZW5kcG9pbnR1cmwiOiJaeVlNeG1WQnArTmJwcU9OMG1jQzFTT1hEK1l4eTVQSDEwRWc0cnRrcWJvPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRBeFlUY3pZVFF0TkRVNU1pMDBaVEU0TFRnd00yVXRZV1poWlRjd1pEWTVaVFEyIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsInNoYXJpbmdpZCI6IkdIYWE4TUNLYUU2VDgxQVBjQVZ2TkEiLCJ0dCI6IjAiLCJpcGFkZHIiOiIxODYuMTkwLjIyNi4zNSJ9.Bhxha8b2_frC5JJTNo9-S0LHEfrpYBHDCPbaNQSesdw&cTag=%22c%3A%7B3EA6833E-EAFB-4AAC-B138-EC782B9F454D%7D%2C2%22&encodeFailures=1&width=256&height=450&srcWidth=256&srcHeight=450', mobile: '../public/mobile/image-from-above.jpg'},
        {one: 'POCKET', two: 'BOREALIS', desktop: 'https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fmakaia-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!pHMaEJJFGE6APq-ucNaeRkfabKWyzh5Oujdv51iLYXtgn0x5alXYRJWndspysbld%2Fitems%2F01RG7JYSJRD774XPLXUNAJDCTFPVRXWCSB%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWFrYWlhLW15LnNoYXJlcG9pbnQuY29tQDBhNzI2YzNlLTI5YzItNDhjMS05ZDNlLWU4OGVjNjUxYzQyMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTQ4MDA4MDAiLCJleHAiOiIxNjk0ODIyNDAwIiwiZW5kcG9pbnR1cmwiOiJaeVlNeG1WQnArTmJwcU9OMG1jQzFTT1hEK1l4eTVQSDEwRWc0cnRrcWJvPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRBeFlUY3pZVFF0TkRVNU1pMDBaVEU0TFRnd00yVXRZV1poWlRjd1pEWTVaVFEyIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsInNoYXJpbmdpZCI6IkdIYWE4TUNLYUU2VDgxQVBjQVZ2TkEiLCJ0dCI6IjAiLCJpcGFkZHIiOiIxODYuMTkwLjIyNi4zNSJ9.Bhxha8b2_frC5JJTNo9-S0LHEfrpYBHDCPbaNQSesdw&cTag=%22c%3A%7BCBFF1F31-77BD-40A3-918A-657D637B0A41%7D%2C2%22&encodeFailures=1&width=256&height=450&srcWidth=256&srcHeight=450', mobile: '../public/mobile/image-pocket-borealis.jpg'},
        {one: 'THE', two: 'CURIOSITY', desktop: 'https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fmakaia-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!pHMaEJJFGE6APq-ucNaeRkfabKWyzh5Oujdv51iLYXtgn0x5alXYRJWndspysbld%2Fitems%2F01RG7JYSL2KX5QLI22TZHKJUDZVDYG5UGC%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWFrYWlhLW15LnNoYXJlcG9pbnQuY29tQDBhNzI2YzNlLTI5YzItNDhjMS05ZDNlLWU4OGVjNjUxYzQyMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTQ4MDA4MDAiLCJleHAiOiIxNjk0ODIyNDAwIiwiZW5kcG9pbnR1cmwiOiJaeVlNeG1WQnArTmJwcU9OMG1jQzFTT1hEK1l4eTVQSDEwRWc0cnRrcWJvPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRBeFlUY3pZVFF0TkRVNU1pMDBaVEU0TFRnd00yVXRZV1poWlRjd1pEWTVaVFEyIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsInNoYXJpbmdpZCI6IkdIYWE4TUNLYUU2VDgxQVBjQVZ2TkEiLCJ0dCI6IjAiLCJpcGFkZHIiOiIxODYuMTkwLjIyNi4zNSJ9.Bhxha8b2_frC5JJTNo9-S0LHEfrpYBHDCPbaNQSesdw&cTag=%22c%3A%7B05FB557A-5AA3-4E9E-A4D0-79A8F06ED0C2%7D%2C2%22&encodeFailures=1&width=256&height=450&srcWidth=256&srcHeight=450', mobile: '../public/mobile/image-curiosity.jpg'},
        {one: 'MAKE IT', two: 'FISHEYE', desktop: 'https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fmakaia-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!pHMaEJJFGE6APq-ucNaeRkfabKWyzh5Oujdv51iLYXtgn0x5alXYRJWndspysbld%2Fitems%2F01RG7JYSIFUC5HJKIBQRB3EUQHWGIVR4Q7%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWFrYWlhLW15LnNoYXJlcG9pbnQuY29tQDBhNzI2YzNlLTI5YzItNDhjMS05ZDNlLWU4OGVjNjUxYzQyMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTQ4MDA4MDAiLCJleHAiOiIxNjk0ODIyNDAwIiwiZW5kcG9pbnR1cmwiOiJaeVlNeG1WQnArTmJwcU9OMG1jQzFTT1hEK1l4eTVQSDEwRWc0cnRrcWJvPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRBeFlUY3pZVFF0TkRVNU1pMDBaVEU0TFRnd00yVXRZV1poWlRjd1pEWTVaVFEyIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jMmQ5YzEzNWYyM2RhNjYzM2UzMmE3ZTdiZDc1MGQwOWIxZGUyYzJiNGMyMDljMmFmMzNkZDUwMDZiMWU5YTlhMSIsInNoYXJpbmdpZCI6IkdIYWE4TUNLYUU2VDgxQVBjQVZ2TkEiLCJ0dCI6IjAiLCJpcGFkZHIiOiIxODYuMTkwLjIyNi4zNSJ9.Bhxha8b2_frC5JJTNo9-S0LHEfrpYBHDCPbaNQSesdw&cTag=%22c%3A%7B74BAA005-01A9-4384-B252-07B19158F21F%7D%2C2%22&encodeFailures=1&width=256&height=450&srcWidth=256&srcHeight=450', mobile: '../public/mobile/image-fisheye.jpg'}
    ];

    return ( 
        <main className="main__container">
            <section className="section__one">
                <figure className="section__figure">
                    <img src="https://southcentralus1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=jpg&cs=fFNQTw&docid=https%3A%2F%2Fmakaia-my.sharepoint.com%3A443%2F_api%2Fv2.0%2Fdrives%2Fb!pHMaEJJFGE6APq-ucNaeRkfabKWyzh5Oujdv51iLYXtgn0x5alXYRJWndspysbld%2Fitems%2F01RG7JYSKVFAEJFX2MI5H23JFUGWZ4YMLQ%3Fversion%3DPublished&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbWFrYWlhLW15LnNoYXJlcG9pbnQuY29tQDBhNzI2YzNlLTI5YzItNDhjMS05ZDNlLWU4OGVjNjUxYzQyMCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2OTQ1NjMyMDAiLCJleHAiOiIxNjk0NTg0ODAwIiwiZW5kcG9pbnR1cmwiOiJaeVlNeG1WQnArTmJwcU9OMG1jQzFTT1hEK1l4eTVQSDEwRWc0cnRrcWJvPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTE2IiwiaXNsb29wYmFjayI6IlRydWUiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTVRBeFlUY3pZVFF0TkRVNU1pMDBaVEU0TFRnd00yVXRZV1poWlRjd1pEWTVaVFEyIiwibmFtZWlkIjoiMCMuZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jNzVhYjNlNmUxYzU4OGNmYmEwODQ1OGUwNzczMjdhZWJlZWZlZTAxZGFhZTZkZjkxNDI5MDIzZmQ2YWIxMzFhZCIsIm5paSI6Im1pY3Jvc29mdC5zaGFyZXBvaW50IiwiaXN1c2VyIjoidHJ1ZSIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWFub24jNzVhYjNlNmUxYzU4OGNmYmEwODQ1OGUwNzczMjdhZWJlZWZlZTAxZGFhZTZkZjkxNDI5MDIzZmQ2YWIxMzFhZCIsInNoYXJpbmdpZCI6InEwZlFCKzFvZkV5N240aGcwSWY3MnciLCJ0dCI6IjAiLCJpcGFkZHIiOiIxODYuMTkwLjIyNi4zNSJ9.6axk8bJikhOttcuBs5LHQm-QCPohrmPv-yH44oz4jIQ&cTag=%22c%3A%7B92082855-4CDF-4F47-ADA4-B435B3CC3170%7D%2C2%22&encodeFailures=1&width=731&height=500&srcWidth=731&srcHeight=500" alt="" />
                </figure>
                <article className="section__article">
                    <h1 className="section__article--title">THE LEADER IN INTERACTIVE VR</h1>
                    <p className="section__article--text">Founded in 2011, Loopstudios has been producing world-class virtual reality projects for some of the best companies around the globe. Our award-winning creations have transformed businesses through digital experiences that bind to their brand.</p>
                </article>
            </section>
            <section className="section__two">
                <article className="section__article--header">
                    <h1 className="section__article--header--title">OUT CREATIONS</h1>
                    <button className="section__article--button">SEE ALL</button>
                </article>
                <article className="section__article--figures">
                    {
                        content.map((element,index) => (
                            <FigureArticle key={index} one={element.one} two={element.two} src={element.mobile} />
                        ))
                    }
                </article>
            </section>
        </main>
    );
}
export default MainContent;